FROM nginx:latest
COPY ./assets /usr/share/nginx/html/assets
COPY ./scripts /usr/share/nginx/html/scripts
COPY ./index.html /usr/share/nginx/html/index.html
COPY default.conf /etc/nginx/conf.d/default.conf
