spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://postgres:5432/pactwars"
    username: pactwars
    password: pactwars
    #initialization-mode: always
spaceships:
  baseurl: http://spaceships:8080
